<?php
$_product = $this->getProduct();
$_brand = $this->getBrand($_product);

$summaryModel = $block->getReviewSummary();

$reviewCount = $summaryModel->getReviewsCount();
if (!$reviewCount) {
    $reviewCount = 0;
}
$ratingSummary = ($summaryModel->getRatingSummary()) ? $summaryModel->getRatingSummary() : 20;
?>
<!-- rich snippets -->
<?php if ($block->wrapWithDiv()): ?>
    <div class="hide-rich-snippets">
<?php endif ?>
    <div itemscope itemtype="https://schema.org/Product">
        <meta itemprop="name" content="<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->stripTags($_product->getName())); ?>" />
        <meta itemprop="image" content="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getImage($_product, 'product_base_image')->getImageUrl()); ?>" />
        <meta itemprop="description" content="<?php /* @escapeNotVerified */ echo $block->escapeQuote($block->stripTags($block->getDescription($_product))); ?>" />
        <meta itemprop="url" content="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getCurrentUrl($_product)); ?>" />
        <meta itemprop="sku" content="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getProduct()->getSku()); ?>" />

        <div itemtype="https://schema.org/AggregateRating" itemscope itemprop="aggregateRating">
            <meta itemprop="worstRating" content="1" />
            <meta itemprop="bestRating" content="5" />
            <meta itemprop="ratingValue" content="<?php echo $ratingSummary / 20 ; ?>" />
            <meta itemprop="reviewCount" content="<?php echo $reviewCount ?>" />
        </div>

        <div itemprop="offers" itemscope itemtype="https://schema.org/Offer">
            <meta itemprop="priceCurrency" content="<?php echo $block->getCurrencyCode() ?>" />
            <meta itemprop="price" content="<?php echo $_product->getFinalPrice(); ?>" />
            <?php if ($_product->isAvailable()): ?>
                <link itemprop="availability" href="https://schema.org/InStock" />
            <?php else : ?>
                <link  itemprop="availability" href="https://schema.org/OutOfStock" />
            <?php endif ?>
        </div>
    </div>
<?php if ($block->wrapWithDiv()): ?>
    </div>
    <style>
        .hide-rich-snippets {display:none;}
    </style>
<?php endif ?>
