<form action="<?php echo $block->getFormAction(); ?>" method="post">
  <h4 class="spcr-bot-20">Contact Details</h4>
  <label for="firstName">First Name</label>
  <input type="text" name="firstName" placeholder="First Name" />
  <label for="lastName">Last Name</label>
  <input type="text" name="lastName" placeholder="Last Name" />
  <label for="userEmail">Email Address</label>
  <input type="email" name="userEmail" placeholder="you@domain.com" />
  <label for="userPhone">Phone #</label>
  <input type="number" name="userPhone" placeholder="" />
  <label for="userTitle">Company Position/Title</label>
  <input type="text" name="userTitle" placeholder="Owner" />

  <h4 class="spcr-top-20 spcr-bot-20">Business Details</h4>
  <label for="companyName">Company Name</label>
  <input type="text" name="companyName" placeholder="Company Name" />
  <label for="companyTaxId">Company Tax ID</label>
  <input type="number" name="companyTaxId" placeholder="companyTaxId" />
  <label for="companyDesc">Company Description</label>
  <textarea type="text" name="companyDesc" placeholder="Company Description">
  </textarea>
  <label for="companyProducts">Types of Products Sold</label>
  <textarea type="text" name="companyProducts" placeholder="Types of products/services your company sells">
  </textarea>
  <label for="companyReferal">Industry Referal</label>
  <input type="text" name="companyReferal" placeholder="Company/Business Name" />
  <label for="companyType">Company Type</label>
  <select>
    <option value="Reseller">Reseller</option>
    <option value="Nonprofit">Non-Profit</option>
  </select>
  <label for="companyAddr">Address</label>
  <input type="text" name="companyAddr" placeholder="Address" />
  <label for="companyCity">City</label>
  <input type="text" name="companyCity" placeholder="City" />
  <label for="companyState">State</label>
  <select name="companyState">
    <option>
      <option value="AL">Alabama</option>
    	<option value="AK">Alaska</option>
    	<option value="AZ">Arizona</option>
    	<option value="AR">Arkansas</option>
    	<option value="CA">California</option>
    	<option value="CO">Colorado</option>
    	<option value="CT">Connecticut</option>
    	<option value="DE">Delaware</option>
    	<option value="DC">District Of Columbia</option>
    	<option value="FL">Florida</option>
    	<option value="GA">Georgia</option>
    	<option value="HI">Hawaii</option>
    	<option value="ID">Idaho</option>
    	<option value="IL">Illinois</option>
    	<option value="IN">Indiana</option>
    	<option value="IA">Iowa</option>
    	<option value="KS">Kansas</option>
    	<option value="KY">Kentucky</option>
    	<option value="LA">Louisiana</option>
    	<option value="ME">Maine</option>
    	<option value="MD">Maryland</option>
    	<option value="MA">Massachusetts</option>
    	<option value="MI">Michigan</option>
    	<option value="MN">Minnesota</option>
    	<option value="MS">Mississippi</option>
    	<option value="MO">Missouri</option>
    	<option value="MT">Montana</option>
    	<option value="NE">Nebraska</option>
    	<option value="NV">Nevada</option>
    	<option value="NH">New Hampshire</option>
    	<option value="NJ">New Jersey</option>
    	<option value="NM">New Mexico</option>
    	<option value="NY">New York</option>
    	<option value="NC">North Carolina</option>
    	<option value="ND">North Dakota</option>
    	<option value="OH">Ohio</option>
    	<option value="OK">Oklahoma</option>
    	<option value="OR">Oregon</option>
    	<option value="PA">Pennsylvania</option>
    	<option value="RI">Rhode Island</option>
    	<option value="SC">South Carolina</option>
    	<option value="SD">South Dakota</option>
    	<option value="TN">Tennessee</option>
    	<option value="TX">Texas</option>
    	<option value="UT">Utah</option>
    	<option value="VT">Vermont</option>
    	<option value="VA">Virginia</option>
    	<option value="WA">Washington</option>
    	<option value="WV">West Virginia</option>
    	<option value="WI">Wisconsin</option>
    	<option value="WY">Wyoming</option>
    </option>
  </select>
  <label for="companyZip">Zipcode</label>
  <input type="number" name="companyZip" placeholder="Zipcode" />
  <label for="companyCountry">Country</label>
  <select name="companyCountry">
    <option>
      United States
    </option>
  </select>

  <input type="submit" class="action submit primary" value="Submit Application" />
</form>
