<form action="<?php echo $this->getUrl('wholesale/') ?>Index/Index/submitForm" method="post">
  <h4 class="spcr-bot-20">Contact Details</h4>
  <label for="firstName">First Name</label>
  <input type="text" name="firstName" placeholder="First Name" />
  <label for="lastName">Last Name</label>
  <input type="text" name="lastName" placeholder="Last Name" />
  <label for="userEmail">Email Address</label>
  <input type="email" name="userEmail" placeholder="you@domain.com" />
  <label for="userPhone">Phone #</label>
  <input type="number" name="userPhone" placeholder="" />
  <label for="userTitle">Company Position/Title</label>
  <input type="text" name="userTitle" placeholder="Owner" />

  <h4 class="spcr-top-20 spcr-bot-20">Business Details</h4>
  <label for="companyName">Company Name</label>
  <input type="text" name="companyName" placeholder="Company Name" />
  <label for="companyTaxId">Company Tax ID</label>
  <input type="number" name="companyTaxId" placeholder="companyTaxId" />
  <label for="companyDesc">Company Description</label>
  <textarea type="text" name="companyDesc" placeholder="Company Description">
  </textarea>
  <label for="companyProducts">Types of Products Sold</label>
  <textarea type="text" name="companyProducts" placeholder="Types of products/services your company sells">
  </textarea>
  <label for="companyReferal">Industry Referal</label>
  <input type="text" name="companyReferal" placeholder="Company/Business Name" />
  <label for="companyType">Company Type</label>
  <select>
    <option>Reseller</option>
    <option>Non-Profit</option>
  </select>
  <label for="companyAddr">Address</label>
  <input type="text" name="companyAddr" placeholder="Address" />
  <label for="companyCity">City</label>
  <input type="text" name="companyCity" placeholder="City" />
  <label for="companyState">State</label>
  <select name="comapnyState">
    <option>
      Select A State
    </option>
  </select>
  <label for="companyZip">Zipcode</label>
  <input type="number" name="companyZip" placeholder="Zipcode" />
  <label for="companyCountry">Country</label>
  <select name="companyCountry">
    <option>
      United States
    </option>
  </select>

  <input type="submit" class="action submit primary" value="Submit Application" />
</form>
