<?php
define('TOOL_CONTAINER_DIR', '/' . APPNAME);
define('TEMPLATE_IMAGE_DIR', ASSET_PATH . "/template");
define('USER_IMAGE_DIR', ASSET_PATH . "/userimg");
define('PREVIEW_IMAGE_DIR', ASSET_PATH . "/previewimg");
define('HTML5_DESIGN_DIR', ASSET_PATH . "/images/designs/");
define('HTML5_PRINT_METHOD_DIR', ASSET_PATH . "/images/printmethod/");
define('HTML5_SHAPE_DIR', ASSET_PATH . "/images/shapes/");
define('HTML5_DISTRESS_DIR', ASSET_PATH . "/images/distress/");
define('HTML5_PALETTE_DIR', ASSET_PATH . "/images/palettes/");
define('HTML5_WORDCLOUD_DIR', ASSET_PATH . "/images/wordcloud/");
define('HTML5_TEXTFX_DIR', ASSET_PATH . "/images/fxfonts/");
define('HTML5_WEBFONTS_DIR', ASSET_PATH . "/images/fonts/");
define('HTML5_USERSLOTS_DIR', ASSET_PATH . "/images/userslots");
define('HTML5_MASK_IMAGE_DIR', ASSET_PATH . "/images/masks/");
define('HTML5_TEXTONPATH_DIR', ASSET_PATH . "/images/textonpaths/");
//define('ORDER_PATH_DIR',ASSET_PATH."/orders");
define('ORDER_PATH_DIR', '/custom-assets/orders');
define('SWATCH_PATH_DIR', ASSET_PATH . "/swatches");
define('LANGUAGE_PATH', '/designer-app');
define('LANGUAGE_DIR', LANGUAGE_PATH . "/languages/");
define('HTML5_PRODUCTTEMPLATE_DIR', ASSET_PATH . "/images/productTemplate/");
define('CAPTURED_IMAGE_DIR', ASSET_PATH . "/images/capturedImage/");
define('USER_WORD_CLOUD_SVG', ASSET_PATH . "/images/userWordCloudSvg/");
define('HTML5_DESIGN_BACKGROUND_DIR', ASSET_PATH . "/images/designsBackGround/");
define('HTML5_BACKGROUND_PATTERN_DIR', ASSET_PATH . "/images/bgPattern/");
define('DOC_ROOT',$_SERVER['DOCUMENT_ROOT']);
define('CART_IMAGE_DIR', ASSET_PATH . "/images/capturedImage/cart/");
define('SHARED_IMAGE_DIR', ASSET_PATH . "/images/capturedImage/shared/");
define('PRE_DECO_PRODUCT_IMAGE_DIR', ASSET_PATH . "/images/capturedImage/preDecoProduct/");
define('TEMPLATE_PREVIEW_IMAGE_DIR', ASSET_PATH . "/images/capturedImage/template/");
define('USERSLOT_PREVIEW_IMAGE_DIR', ASSET_PATH . "/images/capturedImage/userslot/");